/*
ĐỒ ÁN MÔN HỌC AN TOÀN BẢO MẬT DỮ LIỆU TRONG HỆ THỐNG THÔNG TIN
FILE TẠO DATABASE 
NHÓM 9
MSSV        HỌ TÊN          
19127366    Long Mỹ Du
19127377    Nguyễn Huỳnh Khánh Duy
19127476    Trần Thị Huế Minh
*/

-- Xóa tất cả bảng
--DROP TABLE HSBA CASCADE CONSTRAINTS;
--DROP TABLE HSBA_DV CASCADE CONSTRAINTS;
--DROP TABLE BENHNHAN CASCADE CONSTRAINTS;
--DROP TABLE CSYT CASCADE CONSTRAINTS;
--DROP TABLE NHANVIEN CASCADE CONSTRAINTS;
/

-- Tạo bảng
CREATE TABLE HSBA (
    MAHSBA CHAR(8),
    MABN CHAR(8),
    NGAY DATE,
    CHANDOAN NVARCHAR2(100),
    MABS CHAR(6),
    MAKHOA CHAR(6),
    MACSYT CHAR(6),
    KETLUAN NVARCHAR2(200),
	CONSTRAINT HSBA_PK PRIMARY KEY ( MAHSBA )
);

CREATE TABLE HSBA_DV (
    MAHSBA CHAR(8),
    MADV CHAR(6),
    NGAY DATE,
    MAKTV CHAR(6),
    KETQUA NVARCHAR2(200),
	CONSTRAINT HSBA_DV_PK PRIMARY KEY ( MAHSBA, MADV, NGAY )
);


CREATE TABLE BENHNHAN (
	MABN CHAR(8),
	MACSYT CHAR(6),
	TENBN NVARCHAR2(50),
	CMND CHAR(64),
	NGAYSINH DATE,
	SONHA VARCHAR2(20),
	TENDUONG NVARCHAR2(100),
	QUANHUYEN NVARCHAR2(50),
	TINHTP NVARCHAR2(50),
	TIENSUBENH NVARCHAR2(200),
	TIENSUBENHGD NVARCHAR2(200),
	DIUNGTHUOC NVARCHAR2(200),
	CONSTRAINT BENHNHAN_PK PRIMARY KEY ( MABN )

);

CREATE TABLE CSYT(
	MACSYT CHAR(6),
	TENCSYT NVARCHAR2(200),
	DCCSYT NVARCHAR2(200),
	SDTCSYT CHAR(10),
	CONSTRAINT CSYT_PK PRIMARY KEY ( MACSYT )
);

CREATE TABLE NHANVIEN(
	MANV CHAR(6),
	HOTEN NVARCHAR2(50),
	PHAI NVARCHAR2(5),
	NGAYSINH DATE,
	CMND CHAR(64),
	QUEQUAN NVARCHAR2(50),
	SODT CHAR(10),
	CSYT CHAR(6),
	VAITRO NVARCHAR2(20),
	CHUYENKHOA NVARCHAR2(20),
	CONSTRAINT NHANVIEN_PK PRIMARY KEY ( MANV )
);
/

CREATE TABLE CHUYENKHOA(
    MAKHOA CHAR(6),
    TENKHOA NVARCHAR2(20),
    CONSTRAINT CHUYENKHOA_PK PRIMARY KEY ( MAKHOA )
);

CREATE TABLE DICHVU(
    MADV CHAR(6),
    TENDICHVU NVARCHAR2(30),
    CONSTRAINT DICHVU_PK PRIMARY KEY ( MADV)
);

-- Tạo các Foreign key constraints và check constraints
ALTER TABLE HSBA
ADD CONSTRAINT HSBA_BENHNHAN_FK FOREIGN KEY ( MABN )
        REFERENCES BENHNHAN ( MABN )
        ON DELETE CASCADE;
ALTER TABLE HSBA
ADD CONSTRAINT HSBA_NHANVIEN_FK FOREIGN KEY ( MABS )
        REFERENCES NHANVIEN ( MANV )
        ON DELETE CASCADE;

ALTER TABLE HSBA
ADD CONSTRAINT HSBA_CSYT_FK FOREIGN KEY ( MACSYT )
        REFERENCES CSYT ( MACSYT);

ALTER TABLE HSBA
ADD CONSTRAINT HSBA_CHUYENKHOA_FK FOREIGN KEY ( MAKHOA )
        REFERENCES CHUYENKHOA ( MAKHOA );
        
ALTER TABLE HSBA_DV
ADD CONSTRAINT HSBA_DV_HSBA_FK FOREIGN KEY ( MAHSBA )
        REFERENCES HSBA ( MAHSBA )
        ON DELETE CASCADE;

ALTER TABLE HSBA_DV
ADD CONSTRAINT HSBA_DV_DICHVU_FK FOREIGN KEY ( MADV )
        REFERENCES DICHVU ( MADV );
        
ALTER TABLE BENHNHAN
ADD CONSTRAINT BENHNHAN_CSYT_FK FOREIGN KEY ( MACSYT )
        REFERENCES CSYT ( MACSYT);

ALTER TABLE NHANVIEN
ADD CONSTRAINT NHANVIEN_CSYT_FK FOREIGN KEY ( CSYT )
        REFERENCES CSYT ( MACSYT);

ALTER TABLE NHANVIEN
ADD CONSTRAINT NHANVIEN_VAITRO_FK 
	CHECK (VAITRO IN (N'Thanh tra', N'Cơ sở y tế', N'Y sĩ/ bác sĩ', N'Nghiên cứu'));
/

-- Tạo ROLE BENHNHAN
CREATE ROLE ROLE_BENHNHAN NOT IDENTIFIED;
SET ROLE ROLE_BENHNHAN;
GRANT CREATE SESSION TO ROLE_BENHNHAN;
/
-- Tạo ROLE NHANVIEN
CREATE ROLE ROLE_NHANVIEN NOT IDENTIFIED;
SET ROLE ROLE_NHANVIEN;
GRANT CREATE SESSION TO ROLE_NHANVIEN;
/
-- Tạo ROLE YBACSI
CREATE ROLE ROLE_YBACSI;
SET ROLE ROLE_YBACSI;
GRANT CREATE SESSION TO ROLE_YBACSI;
/
-- Tạo ROLE_THANHTRA
CREATE ROLE ROLE_THANHTRA;
SET ROLE ROLE_THANHTRA;
GRANT CREATE SESSION TO ROLE_THANHTRA;
/
--Tạo ROLE_QUANLY
CREATE ROLE ROLE_CSYT;
SET ROLE ROLE_CSYT;
GRANT CREATE SESSION TO ROLE_CSYT;
/
--Tạo ROLE_NGHIENCUU
CREATE ROLE ROLE_NGHIENCUU;
SET ROLE ROLE_NGHIENCUU;
GRANT CREATE SESSION TO ROLE_NGHIENCUU;
