/*
ĐỒ ÁN MÔN HỌC AN TOÀN BẢO MẬT DỮ LIỆU TRONG HỆ THỐNG THÔNG TIN
FILE TẠO DATABASE 
NHÓM 9

MSSV        HỌ TÊN          
19127366    Long Mỹ Du
19127377    Nguyễn Huỳnh Khánh Duy
19127476    Trần Thị Huế Minh
*/

-- Lưu ý: Để có thể sử dụng hàm mã hóa: cần chạy câu lệnh:
-- Grant execute on SYS.DBMS_CRYPTO to QLCSYTE_ADMIN;
-- Lưu ý: Để có thể sử dụng add policy cho VPD: cần chạy câu lệnh:
--grant execute on dbms_rls to QLCSYTE_ADMIN;


-- Xóa tất cả bảng
DROP TABLE HSBA CASCADE CONSTRAINTS;
DROP TABLE HSBA_DV CASCADE CONSTRAINTS;
DROP TABLE BENHNHAN CASCADE CONSTRAINTS;
DROP TABLE CSYT CASCADE CONSTRAINTS;
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;

/
-- Tạo bảng
CREATE TABLE HSBA (
    MAHSBA CHAR(8),
    MABN CHAR(8),
    NGAY DATE,
    CHANDOAN NVARCHAR2(100),
    MABS CHAR(6),
    MAKHOA CHAR(6),
    MACSYT CHAR(6),
    KETLUAN NVARCHAR2(200),
	CONSTRAINT HSBA_PK PRIMARY KEY ( MAHSBA )
);

CREATE TABLE HSBA_DV (
    MAHSBA CHAR(8),
    MADV CHAR(6),
    NGAY DATE,
    MAKTV CHAR(6),
    KETQUA NVARCHAR2(200),
	CONSTRAINT HSBA_DV_PK PRIMARY KEY ( MAHSBA, MADV, NGAY )
);


CREATE TABLE BENHNHAN (
	MABN CHAR(8),
	MACSYT CHAR(6),
	TENBN NVARCHAR2(50),
	CMND CHAR(64),
	NGAYSINH DATE,
	SONHA VARCHAR2(20),
	TENDUONG NVARCHAR2(100),
	QUANHUYEN NVARCHAR2(50),
	TINHTP NVARCHAR2(50),
	TIENSUBENH NVARCHAR2(200),
	TIENSUBENHGD NVARCHAR2(200),
	DIUNGTHUOC NVARCHAR2(200),
	CONSTRAINT BENHNHAN_PK PRIMARY KEY ( MABN )

);

CREATE TABLE CSYT(
	MACSYT CHAR(6),
	TENCSYT NVARCHAR2(200),
	DCCSYT NVARCHAR2(200),
	SDTCSYT CHAR(10),
	CONSTRAINT CSYT_PK PRIMARY KEY ( MACSYT )
);

CREATE TABLE NHANVIEN(
	MANV CHAR(6),
	HOTEN NVARCHAR2(50),
	PHAI NVARCHAR2(5),
	NGAYSINH DATE,
	CMND CHAR(64),
	QUEQUAN NVARCHAR2(50),
	SODT CHAR(10),
	CSYT CHAR(6),
	VAITRO NVARCHAR2(20),
	CHUYENKHOA NVARCHAR2(20),
	CONSTRAINT NHANVIEN_PK PRIMARY KEY ( MANV )
);
/

-- Tạo các Foreign key constraints và check constraints
ALTER TABLE HSBA
ADD CONSTRAINT HSBA_BENHNHAN_FK FOREIGN KEY ( MABN )
        REFERENCES BENHNHAN ( MABN );
ALTER TABLE HSBA
ADD CONSTRAINT HSBA_NHANVIEN_FK FOREIGN KEY ( MABS )
        REFERENCES NHANVIEN ( MANV );
ALTER TABLE HSBA
ADD CONSTRAINT HSBA_CSYT_FK FOREIGN KEY ( MACSYT )
        REFERENCES CSYT ( MACSYT);

ALTER TABLE HSBA_DV
ADD CONSTRAINT HSBA_DV_HSBA_FK FOREIGN KEY ( MAHSBA )
        REFERENCES HSBA ( MAHSBA );

ALTER TABLE BENHNHAN
ADD CONSTRAINT BENHNHAN_CSYT_FK FOREIGN KEY ( MACSYT )
        REFERENCES CSYT ( MACSYT);

ALTER TABLE NHANVIEN
ADD CONSTRAINT NHANVIEN_CSYT_FK FOREIGN KEY ( CSYT )
        REFERENCES CSYT ( MACSYT);
ALTER TABLE NHANVIEN
ADD CONSTRAINT NHANVIEN_VAITRO_FK 
	CHECK (VAITRO IN (N'Thanh tra', N'Cơ sở y tế', N'Y sĩ/ bác sĩ', N'Nghiên cứu'));
/

-- Tạo ROLE Y BÁC SĨ
CREATE ROLE ROLE_YBACSI;
SET ROLE ROLE_YBACSI;


-- Procedure thêm nhân viên
CREATE OR REPLACE PROCEDURE  ThemNhanVien(
    manv IN NHANVIEN.MANV%TYPE,
    hoten  IN NHANVIEN.HOTEN%TYPE,
    phai  IN NHANVIEN.PHAI%TYPE,
    ngaysinh  IN VARCHAR2,
    cmnd  IN NHANVIEN.CMND%TYPE,
    quequan  IN NHANVIEN.QUEQUAN%TYPE,
    sodt  IN NHANVIEN.SODT%TYPE,
    csyt  IN NHANVIEN.CSYT%TYPE,
    vaitro  IN NHANVIEN.VAITRO%TYPE,
    chuyenkhoa  IN NHANVIEN.CHUYENKHOA%TYPE,
    pwd VARCHAR2)
AS
    key_string varchar2(30);
BEGIN
    key_string := manv || ngaysinh;
    INSERT INTO NHANVIEN ("MANV", "HOTEN", "PHAI", "SODT", "NGAYSINH", "QUEQUAN", "CMND", "CSYT", "VAITRO", "CHUYENKHOA") VALUES 
    (manv, hoten, phai, sodt, TO_DATE(ngaysinh,'yyyy-mm-dd'), quequan, ENCRYPT_STRING(cmnd, key_string), csyt, vaitro, chuyenkhoa);
    EXECUTE IMMEDIATE 'CREATE USER "' || MANV || '" IDENTIFIED BY "' || pwd || '"';
    EXECUTE IMMEDIATE 'GRANT ROLE_NHANVIEN TO "' || MANV || '"';
    
    IF (vaitro = N'Y sĩ/ bác sĩ') THEN
        EXECUTE IMMEDIATE 'GRANT ROLE_YBACSI TO "' || MANV || '"';
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE ThemBenhNhan(
    mabn IN BENHNHAN.MABN%TYPE,
    macsyt IN BENHNHAN.MACSYT%TYPE,
    tenbn IN BENHNHAN.TENBN%TYPE,
    cmnd IN BENHNHAN.CMND%TYPE,
    ngaysinh  IN VARCHAR2,
    sonha IN BENHNHAN.SONHA%TYPE,
    tenduong IN BENHNHAN.TENDUONG%TYPE,
    quanhuyen IN BENHNHAN.QUANHUYEN%TYPE,
    tinhtp IN BENHNHAN.TINHTP%TYPE,
    tiensubenh IN BENHNHAN.TIENSUBENH%TYPE,
    tiensubenhgd IN BENHNHAN.TIENSUBENHGD%TYPE,
    diungthuoc IN BENHNHAN.DIUNGTHUOC%TYPE,
    pwd VARCHAR2)
AS
    key_string varchar2(30);
BEGIN
    key_string := mabn || ngaysinh;
    INSERT INTO BENHNHAN VALUES 
    (mabn,macsyt,tenbn,ENCRYPT_STRING(cmnd, key_string),TO_DATE(ngaysinh,'yyyy-mm-dd'),sonha,ENCRYPT_STRING(tenduong, key_string),quanhuyen,tinhtp,tiensubenh,tiensubenhgd,diungthuoc);
    EXECUTE IMMEDIATE 'CREATE USER "' || mabn || '" IDENTIFIED BY "' || pwd || '"';
    EXECUTE IMMEDIATE 'GRANT ROLE_BENHNHAN TO "' || mabn || '"';
END;

/

--TC#4: Sử dụng VPD
--HSBA: Y bác sĩ được xem HSBA mà người này chữa trị 
CREATE OR REPLACE FUNCTION YBS_SEL_HSBA(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MABS = (SELECT MANV FROM NHANVIEN WHERE MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER''))';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLCSYTE_ADMIN','HSBA','ybs_sel_hsba','QLCSYTE_ADMIN','YBS_SEL_HSBA','select');
/
GRANT SELECT ON HSBA TO ROLE_YBACSI;

--HSBA_DV:  Y bác sĩ được xem HSBA_DV mà người này chữa trị 
CREATE OR REPLACE FUNCTION YBS_SEL_HSBA_DV(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
    manv NHANVIEN.MANV%TYPE;
    ngaysinh VARCHAR2(20);
BEGIN

    RETURN 'MAHSBA IN (SELECT MAHSBA FROM HSBA WHERE MABS = (SELECT MANV FROM NHANVIEN WHERE MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')))';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLCSYTE_ADMIN','HSBA_DV','ybs_sel_hsba_dv','QLCSYTE_ADMIN','YBS_SEL_HSBA_DV','select');
/
GRANT SELECT ON HSBA_DV TO ROLE_YBACSI;

--BENHNHAN: Y bác sĩ được xem thông tin bệnh nhân 
CREATE OR REPLACE FUNCTION YBS_SEL_BENHNHAN(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN '((SELECT VAITRO FROM NHANVIEN WHERE MANV = ''' || SYS_CONTEXT('USERENV', 'SESSION_USER') || ''') = N''Y sĩ/ bác sĩ'')';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLCSYTE_ADMIN','BENHNHAN','YBS_SEL_BENHNHAN','QLCSYTE_ADMIN','YBS_SEL_BENHNHAN','select');
/
GRANT SELECT ON BENHNHAN TO ROLE_YBACSI;

