GRANT SELECT ON BENHNHAN TO ROLE_THANHTRA;
GRANT SELECT ON NHANVIEN TO ROLE_THANHTRA;
GRANT SELECT ON HSBA TO ROLE_THANHTRA;
GRANT SELECT ON HSBA_DV TO ROLE_THANHTRA;
GRANT SELECT ON CSYT TO ROLE_THANHTRA;

