--HSBA
CREATE OR REPLACE FUNCTION YBS_SEL_HSBA(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MABS = (SELECT MANV FROM NHANVIEN WHERE CMND = SYS_CONTEXT(''USERENV'', ''SESSION_USER''))';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLCSYTE_ADMIN','HSBA','ybs_sel_hsba','QLCSYTE_ADMIN','YBS_SEL_HSBA','select');
/

--HSBA_DV
CREATE OR REPLACE FUNCTION YBS_SEL_HSBA_DV(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MAHSBA IN (SELECT MAHSBA FROM HSBA WHERE MABS = (SELECT MANV FROM NHANVIEN WHERE CMND = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')))';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLCSYTE_ADMIN','HSBA_DV','ybs_sel_hsba_dv','QLCSYTE_ADMIN','YBS_SEL_HSBA_DV','select');
/
