--TC#4: Sử dụng VPD
--HSBA: Y bác sĩ được xem HSBA mà người này chữa trị 
CREATE OR REPLACE FUNCTION YBS_SEL_HSBA(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MABS = (SELECT MANV FROM NHANVIEN WHERE MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER''))';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLCSYTE_ADMIN','HSBA','ybs_sel_hsba','QLCSYTE_ADMIN','YBS_SEL_HSBA','select');
/
GRANT SELECT ON HSBA TO ROLE_YBACSI;

--HSBA_DV:  Y bác sĩ được xem HSBA_DV mà người này chữa trị 
CREATE OR REPLACE FUNCTION YBS_SEL_HSBA_DV(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
    manv NHANVIEN.MANV%TYPE;
    ngaysinh VARCHAR2(20);
BEGIN

    RETURN 'MAHSBA IN (SELECT MAHSBA FROM HSBA WHERE MABS = (SELECT MANV FROM NHANVIEN WHERE MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER'')))';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLCSYTE_ADMIN','HSBA_DV','ybs_sel_hsba_dv','QLCSYTE_ADMIN','YBS_SEL_HSBA_DV','select');
/
GRANT SELECT ON HSBA_DV TO ROLE_YBACSI;

--BENHNHAN: Y bác sĩ được xem thông tin bệnh nhân (Sử dụng RBAC) 
GRANT SELECT ON BENHNHAN TO ROLE_YBACSI;