CREATE OR REPLACE FUNCTION NVNC_SEL_HSBA(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN
    RETURN 'MAHSBA IN (SELECT BA.MAHSBA FROM HSBA BA, NHANVIEN NV WHERE BA.MACSYT = NV.CSYT AND BA.MAKHOA = NV.CHUYENKHOA AND NV.MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER''))';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLCSYTE_ADMIN','HSBA','nvnc_sel_hsba','QLCSYTE_ADMIN','NVNC_SEL_HSBA','select');
/
GRANT SELECT ON HSBA TO ROLE_NGHIENCUU;

--HSBA_DV:  Y bÃ¡c sÄ© Ä‘Æ°á»£c xem HSBA_DV mÃ  ngÆ°á»�i nÃ y chá»¯a trá»‹ 
CREATE OR REPLACE FUNCTION NVNC_SEL_HSBA_DV(p_schema IN VARCHAR2, p_object IN VARCHAR2)
RETURN VARCHAR2
AS
BEGIN

    RETURN 'MAHSBA IN (SELECT BA.MAHSBA FROM HSBA BA, NHANVIEN NV WHERE BA.MACSYT = NV.CSYT AND BA.MAKHOA = NV.CHUYENKHOA AND NV.MANV = SYS_CONTEXT(''USERENV'', ''SESSION_USER''))';
END;
/
EXEC DBMS_RLS.ADD_POLICY('QLCSYTE_ADMIN','HSBA_DV','ybs_sel_hsba_dv','QLCSYTE_ADMIN','YBS_SEL_HSBA_DV','select');