CREATE OR REPLACE VIEW VW_THONGTINCANHAN_BENHNHAN
AS SELECT MABN, MACSYT, TENBN, DECRYPT_STRING(CMND, MABN || TO_CHAR(NGAYSINH,'yyyy-mm-dd')) AS CMND, NGAYSINH, 
        SONHA, DECRYPT_STRING(TENDUONG, MABN || TO_CHAR(NGAYSINH,'yyyy-mm-dd')) AS TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC
    FROM BENHNHAN
    WHERE MABN = SYS_CONTEXT('userenv', 'session_user')
    WITH CHECK OPTION;
/

CREATE OR REPLACE VIEW VW_THONGTINCANHAN_NHANVIEN
AS SELECT MANV, HOTEN, PHAI, SODT, NGAYSINH, QUEQUAN, DECRYPT_STRING(CMND, MANV || TO_CHAR(NGAYSINH,'yyyy-mm-dd')) AS CMND, 
            CSYT, VAITRO, CHUYENKHOA 
    FROM NHANVIEN
    WHERE MANV = SYS_CONTEXT('userenv', 'session_user')
    WITH CHECK OPTION;
/

GRANT SELECT ON VW_THONGTINCANHAN_BENHNHAN TO ROLE_BENHNHAN;
GRANT UPDATE (MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON VW_THONGTINCANHAN_BENHNHAN TO ROLE_BENHNHAN;

GRANT SELECT ON VW_THONGTINCANHAN_NHANVIEN TO ROLE_NHANVIEN;
GRANT UPDATE (HOTEN, PHAI, SODT, NGAYSINH, QUEQUAN, CMND, CSYT, VAITRO, CHUYENKHOA) ON VW_THONGTINCANHAN_NHANVIEN TO ROLE_NHANVIEN;