CREATE OR REPLACE VIEW VW_THONGTINCANHAN_BENHNHAN
AS SELECT MABN, MACSYT, TENBN, DECRYPT_STRING(CMND, MABN || TO_CHAR(NGAYSINH,'yyyy-mm-dd')) AS CMND, NGAYSINH, 
        SONHA, DECRYPT_STRING(TENDUONG, MABN || TO_CHAR(NGAYSINH,'yyyy-mm-dd')) AS TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC
    FROM BENHNHAN
    WHERE MABN = SYS_CONTEXT('userenv', 'session_user')
    WITH CHECK OPTION;
/

CREATE OR REPLACE VIEW VW_THONGTINCANHAN_NHANVIEN
AS SELECT MANV, HOTEN, PHAI, SODT, NGAYSINH, QUEQUAN, DECRYPT_STRING(CMND, MANV || TO_CHAR(NGAYSINH,'yyyy-mm-dd')) AS CMND, 
            CSYT, VAITRO, CHUYENKHOA 
    FROM NHANVIEN
    WHERE MANV = SYS_CONTEXT('userenv', 'session_user')
    WITH CHECK OPTION;
/

GRANT SELECT ON VW_THONGTINCANHAN_BENHNHAN TO ROLE_BENHNHAN;
GRANT UPDATE (MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON VW_THONGTINCANHAN_BENHNHAN TO ROLE_BENHNHAN;

GRANT SELECT ON VW_THONGTINCANHAN_NHANVIEN TO ROLE_NHANVIEN;
GRANT UPDATE (HOTEN, PHAI, SODT, NGAYSINH, QUEQUAN, CMND, CSYT, VAITRO, CHUYENKHOA) ON VW_THONGTINCANHAN_NHANVIEN TO ROLE_NHANVIEN;
/

CREATE OR REPLACE TRIGGER BN_UPDATE_VW_THONGTINCANHAN
INSTEAD OF UPDATE ON VW_THONGTINCANHAN_BENHNHAN
FOR EACH ROW
DECLARE
BEGIN
    UPDATE BENHNHAN 
    SET MABN = :NEW.MABN, 
        MACSYT = :NEW.MACSYT, 
        TENBN = :NEW.TENBN, 
        CMND = :NEW.CMND,         
        NGAYSINH = :NEW.NGAYSINH,
        SONHA = :NEW.SONHA,
        TENDUONG = :NEW.TENDUONG, 
        QUANHUYEN = :NEW.QUANHUYEN, 
        TINHTP = :NEW.TINHTP, 
        TIENSUBENH = :NEW.TIENSUBENH, 
        TIENSUBENHGD = :NEW.TIENSUBENHGD, 
        DIUNGTHUOC = :NEW.DIUNGTHUOC
    WHERE MABN = :NEW.MABN;
END BN_UPDATE_VW_THONGTINCANHAN;
/

CREATE OR REPLACE TRIGGER NV_UPDATE_VW_THONGTINCANHAN
INSTEAD OF UPDATE ON VW_THONGTINCANHAN_NHANVIEN
FOR EACH ROW
DECLARE
BEGIN
    UPDATE NHANVIEN 
    SET MANV = :NEW.MANV,
        HOTEN = :NEW.HOTEN, 
        PHAI = :NEW.PHAI, 
        SODT = :NEW.SODT, 
        NGAYSINH = :NEW.NGAYSINH, 
        QUEQUAN = :NEW.QUEQUAN,
        CMND = :NEW.CMND,
        CSYT = :NEW.CSYT, 
        VAITRO = :NEW.VAITRO,
        CHUYENKHOA = :NEW.CHUYENKHOA
    WHERE MANV = :NEW.MANV;
END NV_UPDATE_VW_THONGTINCANHAN;
/