CREATE ROLE ROLE_BENHNHAN NOT IDENTIFIED;
SET ROLE ROLE_BENHNHAN;
GRANT CREATE SESSION TO ROLE_BENHNHAN;
/
CREATE ROLE ROLE_NHANVIEN NOT IDENTIFIED;
SET ROLE ROLE_NHANVIEN;
GRANT CREATE SESSION TO ROLE_NHANVIEN;
/
CREATE OR REPLACE VIEW VW_THONGTINCANHAN_BENHNHAN
AS SELECT * FROM BENHNHAN
    WHERE CMND = SYS_CONTEXT('userenv', 'session_user')
    WITH CHECK OPTION;
/

CREATE OR REPLACE VIEW VW_THONGTINCANHAN_NHANVIEN
AS SELECT MANV, HOTEN, PHAI, SODT, NGAYSINH, QUEQUAN, CMND, CSYT, VAITRO, CHUYENKHOA FROM NHANVIEN
    WHERE CMND = SYS_CONTEXT('userenv', 'session_user')
    WITH CHECK OPTION;
/

GRANT SELECT ON VW_THONGTINCANHAN_BENHNHAN TO ROLE_BENHNHAN;
GRANT UPDATE (MACSYT, TENBN, CMND, NGAYSINH, SONHA, TENDUONG, QUANHUYEN, TINHTP, TIENSUBENH, TIENSUBENHGD, DIUNGTHUOC) ON VW_THONGTINCANHAN_BENHNHAN TO ROLE_BENHNHAN;

GRANT SELECT ON VW_THONGTINCANHAN_NHANVIEN TO ROLE_NHANVIEN;
GRANT UPDATE (HOTEN, PHAI, SODT, NGAYSINH, QUEQUAN, CMND, CSYT, VAITRO, CHUYENKHOA) ON VW_THONGTINCANHAN_NHANVIEN TO ROLE_NHANVIEN;
