select * from QLCSYTE_ADMIN.VW_THONGTINCANHAN_NHANVIEN;

update QLCSYTE_ADMIN.VW_THONGTINCANHAN_NHANVIEN
set ngaysinh = TO_DATE('1996-01-29','yyyy-mm-dd');

update QLCSYTE_ADMIN.VW_THONGTINCANHAN_NHANVIEN
set manv = 'NV0102';

commit;

