--By default, LBACSYS is locked, using CDB SYS to unlock and change password, can't use CDB SYS
ALTER USER LBACSYS ACCOUNT UNLOCK IDENTIFIED BY LBACSYS;
--Connect as LBACSYS, grant needed privileges to QLCSYTE_ADMIN
--GRANT EXECUTE ON sa_components TO QLCSYTE_ADMIN;
--GRANT EXECUTE ON sa_user_admin TO QLCSYTE_ADMIN;
--GRANT EXECUTE ON sa_label_admin TO QLCSYTE_ADMIN;
--GRANT EXECUTE ON sa_policy_admin TO QLCSYTE_ADMIN;
--GRANT EXECUTE ON sa_audit_admin  TO QLCSYTE_ADMIN;
--GRANT EXECUTE ON char_to_label TO QLCSYTE_ADMIN;
--GRANT LBAC_DBA TO QLCSYTE_ADMIN;
--GRANT EXECUTE ON sa_sysdba TO QLCSYTE_ADMIN;
--GRANT EXECUTE ON to_lbac_data_label TO QLCSYTE_ADMIN;

--EXEC SA_SYSDBA.DROP_POLICY ('soyte_policy', TRUE);
EXEC SA_SYSDBA.CREATE_POLICY(policy_name => 'soyte_policy', column_name => 'soyte_label');
/
--EXEC SA_COMPONENTS.DROP_LEVEL ('soyte_policy',20);
EXEC SA_COMPONENTS.CREATE_LEVEL('soyte_policy',20,'YBS','Y Bac si');
--EXEC SA_COMPONENTS.DROP_LEVEL ('soyte_policy',40);
EXEC SA_COMPONENTS.CREATE_LEVEL('soyte_policy',40,'GDCSYT','Giam doc co so y te');
--EXEC SA_COMPONENTS.DROP_LEVEL ('soyte_policy',60);
EXEC SA_COMPONENTS.CREATE_LEVEL('soyte_policy',60,'GDS','Giam doc so');
/
--EXEC SA_COMPONENTS.DROP_COMPARTMENT('soyte_policy',20);
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('soyte_policy',20,'DTCS','Dieu tri chuyen sau');
--EXEC SA_COMPONENTS.DROP_COMPARTMENT('soyte_policy',40);
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('soyte_policy',40,'DTNT','Dieu tri noi tru');
--EXEC SA_COMPONENTS.DROP_COMPARTMENT('soyte_policy',60);
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('soyte_policy',60,'DTNGT','Dieu tri ngoai tru');
/
--EXEC SA_COMPONENTS.DROP_GROUP('soyte_policy',20);
EXEC SA_COMPONENTS.CREATE_GROUP('soyte_policy',20,'TP','Thanh pho');
--EXEC SA_COMPONENTS.DROP_GROUP('soyte_policy',40);
EXEC SA_COMPONENTS.CREATE_GROUP('soyte_policy',40,'TT','Trung tam','TP');
--EXEC SA_COMPONENTS.DROP_GROUP('soyte_policy',60);
EXEC SA_COMPONENTS.CREATE_GROUP('soyte_policy',60,'CTT','Can trung tam','TP');
--EXEC SA_COMPONENTS.DROP_GROUP('soyte_policy',80);
EXEC SA_COMPONENTS.CREATE_GROUP('soyte_policy',80,'NT','Ngoai thanh','TP');
/

EXEC SA_USER_ADMIN.SET_USER_PRIVS('soyte_policy','QLCSYTE_ADMIN','FULL,PROFILE_ACCESS');
/
--Connect as QLCSYTE_ADMIN
CREATE TABLE THONGBAO (
    MATB CHAR(8),
    NDUNG NVARCHAR2(1000),
    NGIO TIMESTAMP,
    DDIEM NVARCHAR2(100)
);
--Connect as LBACSYS
BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
policy_name   => 'soyte_policy',
schema_name   => 'QLCSYTE_ADMIN',
table_name    => 'THONGBAO',
table_options => 'NO_CONTROL');
END;
/
--Connect as QLCSYTE_ADMIN
GRANT SELECT, INSERT, UPDATE, DELETE ON THONGBAO TO PUBLIC;
--REVOKE SELECT, INSERT, UPDATE, DELETE ON THONGBAO FROM PUBLIC;

INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000001', 'NOI DUNG 1', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 1', CHAR_TO_LABEL('soyte_policy','GDS'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000002', 'NOI DUNG 2', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 2', CHAR_TO_LABEL('soyte_policy','GDCSYT:DTCS:TT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000003', 'NOI DUNG 3', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 3', CHAR_TO_LABEL('soyte_policy','GDCSYT:DTCS:CTT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000004', 'NOI DUNG 4', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 4', CHAR_TO_LABEL('soyte_policy','GDCSYT:DTCS:NT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000005', 'NOI DUNG 5', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 5', CHAR_TO_LABEL('soyte_policy','GDCSYT:DTNGT:TT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000006', 'NOI DUNG 6', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 6', CHAR_TO_LABEL('soyte_policy','GDCSYT:DTNGT:CTT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000007', 'NOI DUNG 7', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 7', CHAR_TO_LABEL('soyte_policy','GDCSYT:DTNGT:NT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000008', 'NOI DUNG 8', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 8', CHAR_TO_LABEL('soyte_policy','GDCSYT:DTNT:TT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000009', 'NOI DUNG 9', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 9', CHAR_TO_LABEL('soyte_policy','GDCSYT:DTNT:CTT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000010', 'NOI DUNG 10', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 10', CHAR_TO_LABEL('soyte_policy','GDCSYT:DTNT:NT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000011', 'NOI DUNG 11', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 11', CHAR_TO_LABEL('soyte_policy','YBS:DTCS:TT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000012', 'NOI DUNG 12', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 12', CHAR_TO_LABEL('soyte_policy','YBS:DTCS:CTT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000013', 'NOI DUNG 13', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 13', CHAR_TO_LABEL('soyte_policy','YBS:DTCS:NT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000014', 'NOI DUNG 14', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 14', CHAR_TO_LABEL('soyte_policy','YBS:DTNGT:TT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000015', 'NOI DUNG 15', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 15', CHAR_TO_LABEL('soyte_policy','YBS:DTNGT:CTT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000016', 'NOI DUNG 16', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 16', CHAR_TO_LABEL('soyte_policy','YBS:DTNGT:NT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000017', 'NOI DUNG 17', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 17', CHAR_TO_LABEL('soyte_policy','YBS:DTNT:TT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000018', 'NOI DUNG 18', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 18', CHAR_TO_LABEL('soyte_policy','YBS:DTNT:CTT'));
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM, SOYTE_LABEL)
VALUES ('TB000019', 'NOI DUNG 19', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 19', CHAR_TO_LABEL('soyte_policy','YBS:DTNT:NT'));

--Connect as LBACSYS
BEGIN
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY('soyte_policy','QLCSYTE_ADMIN','THONGBAO');
SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
policy_name   => 'soyte_policy',
schema_name   => 'QLCSYTE_ADMIN',
table_name    => 'THONGBAO',
table_options => 'READ_CONTROL,WRITE_CONTROL,CHECK_CONTROL');
END;
/

BEGIN
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0056','GDS:DTCS,DTNT,DTNGT:TP');
  
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0057','GDCSYT:DTCS,DTNT,DTNGT:TT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0058','GDCSYT:DTCS,DTNT,DTNGT:CTT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0059','GDCSYT:DTCS,DTNT,DTNGT:NT');

  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0026','YBS:DTCS:TT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0035','YBS:DTCS:TT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0027','YBS:DTCS:CTT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0036','YBS:DTCS:CTT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0028','YBS:DTCS:NT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0037','YBS:DTCS:NT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0029','YBS:DTNT:TT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0038','YBS:DTNT:TT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0030','YBS:DTNT:CTT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0039','YBS:DTNT:CTT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0031','YBS:DTNT:NT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0040','YBS:DTNT:NT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0032','YBS:DTNGT:TT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0041','YBS:DTNGT:TT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0033','YBS:DTNGT:CTT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0042','YBS:DTNGT:CTT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0034','YBS:DTNGT:NT');
  SA_USER_ADMIN.SET_USER_LABELS('soyte_policy','NV0043','YBS:DTNGT:NT');
END;
/
--drop table thongbao;