--By default, LBACSYS is locked, using CDB SYS to unlock and change password, can't use CDB SYS
ALTER USER LBACSYS IDENTIFIED BY LBACSYS ACCOUNT UNLOCK;
--Connect as LBACSYS, grant needed privileges to QLCSYTE_ADMIN
GRANT LBAC_DBA TO QLCSYTE_ADMIN;
GRANT EXECUTE ON sa_sysdba TO QLCSYTE_ADMIN;
GRANT EXECUTE ON to_lbac_data_label TO QLCSYTE_ADMIN;
GRANT EXECUTE ON sa_components TO QLCSYTE_ADMIN;
GRANT EXECUTE ON sa_user_admin TO QLCSYTE_ADMIN;
GRANT EXECUTE ON sa_label_admin TO QLCSYTE_ADMIN;
GRANT EXECUTE ON sa_policy_admin TO QLCSYTE_ADMIN;
GRANT EXECUTE ON sa_audit_admin  TO QLCSYTE_ADMIN;
GRANT EXECUTE ON char_to_label TO QLCSYTE_ADMIN;

--Connect as QLCSYTE_ADMIN
--EXEC SA_SYSDBA.DROP_POLICY ('soyte_policy', TRUE);
EXEC SA_SYSDBA.CREATE_POLICY(policy_name => 'soyte_policy', column_name => 'soyte_label');


--EXEC SA_COMPONENTS.DROP_LEVEL ('soyte_policy',20);
EXEC SA_COMPONENTS.CREATE_LEVEL('soyte_policy',20,'YBS','Y Bac si');
--EXEC SA_COMPONENTS.DROP_LEVEL ('soyte_policy',40);
EXEC SA_COMPONENTS.CREATE_LEVEL('soyte_policy',40,'GDCSYT','Giam doc co so y te');
--EXEC SA_COMPONENTS.DROP_LEVEL ('soyte_policy',60);
EXEC SA_COMPONENTS.CREATE_LEVEL('soyte_policy',60,'GDS','Giam doc so');
/
--EXEC SA_COMPONENTS.DROP_COMPARTMENT('soyte_policy',20);
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('soyte_policy',20,'DTCS','Dieu tri chuyen sau');
--EXEC SA_COMPONENTS.DROP_COMPARTMENT('soyte_policy',40);
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('soyte_policy',40,'DTNT','Dieu tri noi tru');
--EXEC SA_COMPONENTS.DROP_COMPARTMENT('soyte_policy',60);
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('soyte_policy',60,'DTNGT','Dieu tri ngoai tru');
/
--EXEC SA_COMPONENTS.DROP_GROUP('soyte_policy',20);
EXEC SA_COMPONENTS.CREATE_GROUP('soyte_policy',20,'TP','Thanh pho');
--EXEC SA_COMPONENTS.DROP_GROUP('soyte_policy',40);
EXEC SA_COMPONENTS.CREATE_GROUP('soyte_policy',40,'TT','Trung tam','TP');
--EXEC SA_COMPONENTS.DROP_GROUP('soyte_policy',60);
EXEC SA_COMPONENTS.CREATE_GROUP('soyte_policy',60,'CTT','Can trung tam','TP');
--EXEC SA_COMPONENTS.DROP_GROUP('soyte_policy',80);
EXEC SA_COMPONENTS.CREATE_GROUP('soyte_policy',80,'NT','Ngoai thanh','TP');
/

EXEC SA_USER_ADMIN.SET_USER_PRIVS('soyte_policy','QLCSYTE_ADMIN','FULL,PROFILE_ACCESS');
/

CREATE TABLE THONGBAO (
    MATB CHAR(8),
    NDUNG NVARCHAR2(1000),
    NGIO TIMESTAMP,
    DDIEM NVARCHAR2(100)
);

INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM)
VALUES ('TB000001', 'NOI DUNG 1', TO_TIMESTAMP('2022-01-01 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 1');
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM)
VALUES ('TB000002', 'NOI DUNG 2', TO_TIMESTAMP('2022-02-02 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 2');
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM)
VALUES ('TB000003', 'NOI DUNG 3', TO_TIMESTAMP('2022-03-03 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 3');
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM)
VALUES ('TB000004', 'NOI DUNG 4', TO_TIMESTAMP('2022-04-04 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 4');
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM)
VALUES ('TB000005', 'NOI DUNG 5', TO_TIMESTAMP('2022-05-05 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 5');
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM)
VALUES ('TB000006', 'NOI DUNG 6', TO_TIMESTAMP('2022-06-06 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 6');
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM)
VALUES ('TB000007', 'NOI DUNG 7', TO_TIMESTAMP('2022-07-07 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 7');
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM)
VALUES ('TB000008', 'NOI DUNG 8', TO_TIMESTAMP('2022-08-08 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 8');
INSERT INTO THONGBAO (MATB, NDUNG, NGIO, DDIEM)
VALUES ('TB000009', 'NOI DUNG 9', TO_TIMESTAMP('2022-09-09 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'DIA DIEM 9');


BEGIN
  SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    policy_name   => 'soyte_policy',
    schema_name   => 'QLCSYTE_ADMIN',
    table_name    => 'THONGBAO',
    table_options => 'NO_CONTROL');
END;
/